apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hasura-console
  namespace: 5stack
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${HASURA_DOMAIN}
      secretName: 5stack-ssl
  rules:
    - host: ${HASURA_DOMAIN}
      http:
        paths:
          - backend:
              service:
                name: hasura
                port:
                  number: 8080
            path: /
            pathType: Prefix
